import fs from 'node:fs';
import path from 'node:path';
import { outputBaseName } from '../pipeline/session.js';
import { logger } from '../utils/logger.js';

const GROQ_URL = 'https://api.groq.com/openai/v1/chat/completions';

const SECTION_INSTRUCTIONS = {
  summary: '## Summary\nA concise 3-6 sentence overview of the meeting.',
  actionItems: '## Action Items\nA bulleted list of concrete to-dos / follow-ups. Note the owner in **bold** when identifiable (use the speaker labels). Write "None identified." if there are none.',
  keyDecisions: '## Key Decisions\nA bulleted list of decisions made or conclusions reached. Write "None identified." if there are none.',
  topicsQuestions: '## Topics & Open Questions\nMain topics discussed (brief bullets) followed by any unresolved/open questions raised.',
};

const SECTION_ORDER = ['summary', 'actionItems', 'keyDecisions', 'topicsQuestions'];

/** Build the system prompt from the selected section keys. */
function buildSystemPrompt(sections) {
  const chosen = SECTION_ORDER.filter((s) => sections.includes(s));
  const blocks = chosen.map((s) => SECTION_INSTRUCTIONS[s]).join('\n\n');
  return [
    'You are an assistant that extracts insights from a meeting transcript.',
    'The transcript labels speakers (e.g. "Me" and "Participants"). Use those labels where relevant.',
    'Respond in GitHub-flavored Markdown using EXACTLY the following sections, in this order,',
    'and nothing else (no preamble, no closing remarks):',
    '',
    blocks,
  ].join('\n');
}

/**
 * Generate insights for a transcript via the Groq API.
 * @returns {Promise<string>} the insights as Markdown.
 */
export async function generateInsights({ transcriptText, title, apiKey, model, sections }) {
  if (!apiKey) throw new Error('No Groq API key set. Add it in Settings (or config "groq.apiKey").');
  if (!transcriptText || !transcriptText.trim()) throw new Error('Transcript is empty — nothing to analyze.');

  const body = {
    model,
    temperature: 0.3,
    messages: [
      { role: 'system', content: buildSystemPrompt(sections) },
      { role: 'user', content: `Meeting title: ${title || 'Untitled'}\n\nTranscript:\n\n${transcriptText}` },
    ],
  };

  let res;
  try {
    res = await fetch(GROQ_URL, {
      method: 'POST',
      headers: { Authorization: `Bearer ${apiKey}`, 'Content-Type': 'application/json' },
      body: JSON.stringify(body),
    });
  } catch (err) {
    throw new Error(`Could not reach Groq (${err.message}). Check your internet connection.`);
  }

  if (!res.ok) {
    const detail = await res.text().catch(() => '');
    if (res.status === 401) throw new Error('Groq rejected the API key (401). Check it in Settings.');
    if (res.status === 429) throw new Error('Groq rate limit reached (429). Wait a bit and try again.');
    throw new Error(`Groq API error ${res.status}: ${detail.slice(0, 300)}`);
  }

  const data = await res.json();
  const content = data?.choices?.[0]?.message?.content?.trim();
  if (!content) throw new Error('Groq returned an empty response.');
  return content;
}

/**
 * Generate insights for a session's transcript and write <id>.insights.md.
 * @returns {Promise<string>} path to the written insights file.
 */
export async function writeInsightsForSession(cfg, session) {
  const groq = cfg.groq || {};
  const mdPath = path.join(cfg.resolved.transcripts, `${outputBaseName(session)}.md`);
  if (!fs.existsSync(mdPath)) throw new Error(`Transcript not found: ${mdPath}`);
  const transcriptText = fs.readFileSync(mdPath, 'utf8');

  logger.step(`Generating insights with Groq (${groq.model})…`);
  const insights = await generateInsights({
    transcriptText,
    title: session.title,
    apiKey: groq.apiKey,
    model: groq.model,
    sections: groq.sections || ['summary', 'actionItems', 'keyDecisions', 'topicsQuestions'],
  });

  const header = `# Insights — ${session.title}\n\n- **Date:** ${session.date}\n- **Generated by:** Groq (${groq.model})\n\n---\n\n`;
  const outPath = path.join(cfg.resolved.transcripts, `${outputBaseName(session)}.insights.md`);
  fs.writeFileSync(outPath, header + insights + '\n', 'utf8');
  logger.success(`Insights: ${outPath}`);
  return outPath;
}
